// <auto-generated />
using System;
using FleetControlWebAPI.Models.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FleetControlWebAPI.Migrations
{
    [DbContext(typeof(ControleFrotaContext))]
    [Migration("20230404001547_InsertDeDados")]
    partial class InsertDeDados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.Motorista", b =>
                {
                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnName("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnName("cnh")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnName("validadeCNH")
                        .HasColumnType("datetime");

                    b.HasKey("MotoristaId");

                    b.ToTable("tbl_motor");

                    b.HasData(
                        new
                        {
                            MotoristaId = "dd761061-f588-4cbc-a06e-d88f7559c4f0",
                            Ativo = true,
                            CNH = "1234567891",
                            Nome = "Samuel Almeida",
                            ValidadeCNH = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MotoristaId = "24ee7c1d-8969-4094-8ff4-92d4c3a30c1a",
                            Ativo = true,
                            CNH = "9876549283",
                            Nome = "João da Silva",
                            ValidadeCNH = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("VeiculoId", "MotoristaId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("tbl_motr_veicl");

                    b.HasData(
                        new
                        {
                            VeiculoId = "fdf2bbd9-7cdf-4d71-98d2-94a32c9dd100",
                            MotoristaId = "dd761061-f588-4cbc-a06e-d88f7559c4f0"
                        },
                        new
                        {
                            VeiculoId = "0ba3f5d5-c6c4-485c-aa95-b0dd3e0625e3",
                            MotoristaId = "24ee7c1d-8969-4094-8ff4-92d4c3a30c1a"
                        });
                });

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ano")
                        .HasColumnName("ano")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa")
                        .HasColumnName("placa")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VeiculoId");

                    b.ToTable("tbl_veicl");

                    b.HasData(
                        new
                        {
                            VeiculoId = "fdf2bbd9-7cdf-4d71-98d2-94a32c9dd100",
                            Ano = 2019,
                            Modelo = "Volvo FH 540",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            VeiculoId = "0ba3f5d5-c6c4-485c-aa95-b0dd3e0625e3",
                            Ano = 2018,
                            Modelo = "Scania R450",
                            Placa = "CBA4321"
                        });
                });

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.HasOne("FleetControlWebAPI.Models.Domain.Entities.Motorista", "Motorista")
                        .WithMany("Veiculos")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetControlWebAPI.Models.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Motoristas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
