// <auto-generated />
using System;
using FleetControlWebAPI.Models.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FleetControlWebAPI.Migrations
{
    [DbContext(typeof(ControleFrotaContext))]
    partial class ControleFrotaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.Motorista", b =>
                {
                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnName("ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNH")
                        .IsRequired()
                        .HasColumnName("cnh")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("ValidadeCNH")
                        .HasColumnName("validadeCNH")
                        .HasColumnType("datetime");

                    b.HasKey("MotoristaId");

                    b.ToTable("tbl_motor");

                    b.HasData(
                        new
                        {
                            MotoristaId = "dc1398ac-bf6b-4cd6-9d9b-b1a50c24ad65",
                            Ativo = true,
                            CNH = "1234567891",
                            Nome = "Samuel Almeida",
                            ValidadeCNH = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MotoristaId = "05df018c-4e86-4327-8f3a-6f72c8c15bc9",
                            Ativo = true,
                            CNH = "9876549283",
                            Nome = "João da Silva",
                            ValidadeCNH = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MotoristaId")
                        .HasColumnName("motor_id")
                        .HasColumnType("varchar(50)");

                    b.HasKey("VeiculoId", "MotoristaId");

                    b.HasIndex("MotoristaId");

                    b.ToTable("tbl_motr_veicl");

                    b.HasData(
                        new
                        {
                            VeiculoId = "8d93e52d-36df-4c6b-9505-239a9ac54966",
                            MotoristaId = "dc1398ac-bf6b-4cd6-9d9b-b1a50c24ad65"
                        },
                        new
                        {
                            VeiculoId = "bfd9f2db-032a-4dbe-8a07-019aab9f29ae",
                            MotoristaId = "05df018c-4e86-4327-8f3a-6f72c8c15bc9"
                        });
                });

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.Veiculo", b =>
                {
                    b.Property<string>("VeiculoId")
                        .HasColumnName("veicl_id")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ano")
                        .HasColumnName("ano")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa")
                        .HasColumnName("placa")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VeiculoId");

                    b.ToTable("tbl_veicl");

                    b.HasData(
                        new
                        {
                            VeiculoId = "8d93e52d-36df-4c6b-9505-239a9ac54966",
                            Ano = 2019,
                            Modelo = "Volvo FH 540",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            VeiculoId = "bfd9f2db-032a-4dbe-8a07-019aab9f29ae",
                            Ano = 2018,
                            Modelo = "Scania R450",
                            Placa = "CBA4321"
                        });
                });

            modelBuilder.Entity("FleetControlWebAPI.Models.Domain.Entities.MotoristaVeiculo", b =>
                {
                    b.HasOne("FleetControlWebAPI.Models.Domain.Entities.Motorista", "Motorista")
                        .WithMany("Veiculos")
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetControlWebAPI.Models.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("Motoristas")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
